baseURL = "https://www.abdullah.com.bd"
title = "Abdullah's web"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 15
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "MD, Abdullah"
description = "Abdullah's personal website"
keywords = "blog,developer,personal, C#, Desktop App, .NET, HUGO"
info = ["I write code & care about my Privacyüõ°Ô∏è"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
footerContent = "‚úçÔ∏è with ‚ù§Ô∏è by Md. Abdullah"
dateFormat = "2 January, 2006"
hideFooter = true
hideCredits = false
hideCopyright = false
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = true
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive ‚Äì defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"



[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/abdullah-cse"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 2
url = "https://twitter.com/johndoe/"

[[params.social]]
name = "Youtube"
icon = "fa fa-youtube-play"
weight = 3
url = "https://www.youtube.com/channel/UCh_ciK6TZyD-3dgx6QThabw"

[[params.social]]
name = "Telegram"
icon = "fa fa-telegram"
weight = 4
url = "https://t.me/abdullahcse"

[[params.social]]
name = "Protonmail"
icon = "fa fa-envelope"
weight = 5
url = "mailto:contact@abdullah.com.bd"



[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "Now"
weight = 1
url = "now/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Uses"
weight = 4
url = "uses/"

[[languages.en.menu.main]]
name = "About"
weight = 5
url = "about/"


#‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æ ‡¶≠‡¶æ‡¶∑‡¶æ‡¶∞ ‡¶Ö‡¶Ç‡¶∂ ‡¶∂‡ßÅ‡¶∞‡ßÅ
[languages.bn]
languageName = "‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æ"
title = "‡¶Ü‡¶¨‡¶¶‡ßÅ‡¶≤‡ßç‡¶≤‡¶æ‡¶π'‡¶∞ ‡¶®‡ßã‡¶ü"

[languages.bn.params]
author = "‡¶Æ‡ßã. ‡¶Ü‡¶¨‡¶¶‡ßÅ‡¶≤‡ßç‡¶≤‡¶æ‡¶π"
info = "C# ‡¶°‡ßá‡¶≠‡ßá‡¶≤‡¶™‡¶æ‡¶∞"
description = "S√≠tio pessoal de Jo√£o Ningu√©m"
keywords = "blog, C#, pessoal, Tutorial, developer "
footerContent = "‡¶ï‡¶æ‡¶≤‡¶ï‡ßá‡¶∞ ‡¶¶‡¶ø‡¶®‡¶ü‡¶ø‡¶á ‡¶õ‡¶ø‡¶≤‡ßã ‡¶∏‡¶π‡¶ú ‡¶¶‡¶ø‡¶®"

[[languages.bn.menu.main]]
name = "‡¶è‡¶ñ‡¶®"
weight = 1
url = "now/"

[[languages.bn.menu.main]]
name = "‡¶≤‡ßá‡¶ñ‡¶æ‡¶≤‡ßá‡¶ñ‡¶ø"
weight = 2
url = "posts/"

[[languages.bn.menu.main]]
name = "‡¶™‡ßç‡¶∞‡¶ï‡¶≤‡ßç‡¶™"
weight = 3
url = "projects/"

[[languages.bn.menu.main]]
name = "‡¶¨‡ßç‡¶Ø‡¶¨‡¶π‡¶æ‡¶∞"
weight = 4
url = "uses/"

[[languages.bn.menu.main]]
name = "‡¶Ü‡¶Æ‡¶æ‡¶∞ ‡¶∏‡¶Æ‡¶®‡ßç‡¶ß‡ßá"
weight = 5
url = "about/"
#‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æ ‡¶≠‡¶æ‡¶∑‡¶æ‡¶∞ ‡¶Ö‡¶Ç‡¶∂ ‡¶∂‡ßá‡¶∑



#‡¶Ü‡¶∞‡¶¨‡ßÄ ‡¶≠‡¶æ‡¶∑‡¶æ ‡¶∂‡ßÅ‡¶∞‡ßÅ
[languages.ar]
rtl = true  #‡¶°‡¶æ‡¶®‡¶™‡¶æ‡¶∂ ‡¶•‡ßá‡¶ï‡ßá ‡¶Ü‡¶∞‡¶¨‡ßÄ ‡¶¶‡ßá‡¶ñ‡¶æ‡¶®‡ßã‡¶∞ ‡¶ú‡¶®‡ßç‡¶Ø‡•§
languageName = "ÿπÿ±ÿ®Ÿâ"
title = "ÿ¥ÿ®ŸÉÿ© ÿπÿ®ÿØ ÿßŸÑŸÑŸá"

[languages.ar.params]
author = "‡¶Æ‡ßã. ‡¶Ü‡¶¨‡¶¶‡ßÅ‡¶≤‡ßç‡¶≤‡¶æ‡¶π"
info = "ÿ£ŸÉÿ™ÿ® ÿ±ŸÖÿ≤Ÿãÿß Ÿàÿ£Ÿáÿ™ŸÖ ÿ®ÿÆÿµŸàÿµŸäÿ™Ÿä"
description = "‡¶Ü‡¶≤‡¶π‡¶æ‡¶Æ‡¶¶‡ßÅ‡¶≤‡¶ø‡¶≤‡ßç‡¶≤‡¶æ‡¶π"
keywords = "blog,desenvolvedor,pessoal"
footerContent = "Nothing to hide"



[[languages.ar.menu.main]]
name = "ŸÖÿØŸàŸÜÿ©"
weight = 2
url = "posts/"

[[languages.ar.menu.main]]
name = "ÿßŸÑŸÖÿ¥ÿßÿ±Ÿäÿπ"
weight = 3
url = "projects/"

[[languages.ar.menu.main]]
name = "ÿ™ŸàÿßÿµŸÑ"
weight = 5
url = "contact/"

[[languages.ar.menu.main]]
name = "ÿπŸÜŸä"
weight = 6
url = "about/"
#‡¶Ü‡¶∞‡¶¨‡ßÄ ‡¶≠‡¶æ‡¶∑‡¶æ ‡¶∂‡ßá‡¶∑
